import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { LogInButton } from '../components/flow';
import { useCurrentUser } from "../hooks/flow/useCurrentUser";

export default function Home() {
  const { currentUser, openIDData } = useCurrentUser();
  console.debug('user => ', currentUser, openIDData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div style={{
            paddingBottom: "12px",
          }}>
            <p>Current user is {currentUser?.addr || 'unknown'}.</p>
            {currentUser?.loggedIn && <p>Email: {openIDData?.email || 'unknown'}</p>}
          </div>
          <LogInButton />
        </div>
      </main>
    </>
  );
}
